linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - misspell
    - gofmt
    - gosec
    - bodyclose
    - errorlint

run:
  skip-dirs:
    - vendor
